### PR TITLE
Remove To Do s

### PR DESCRIPTION
**Pull request by akaztp**
The To Do's are now on `to-do.ms` but they should be hidden somehow from the .zip to deliver to the candidate 30min before tech interview. Not sure how can this "hide" be done:
- PDF to share on the meeting
  - I don't like to have it separately... it will get out of sync!
- only include it in a named branch
  - Can the candidate still reach the repo, and the branch? 
  - Should we continue to have the repo public?
  - Can we "privatize" the repo keeping access to the .zip?
- encrypt?

### CODE REVIEW

**Comment by gilM2030** [comment]
If we really want the candidates not to see the todos, then we need to rebase this repo or recreate it because the file is already in git history :D.

If we only want to _hide_ it, we could just send them a branch link instead of master. If we want to hide it from the zip and we can't make a zip of the branch, we could manually make the zip from a Makefile that doesn't include the todo file, or maybe from a branch that doesn't contain it.

**Comment by akaztp** [comment]
Thanks, but I have more doubts about your comment than my initial issues...

Ok, tell me how can we all:
1. Send the candidate the latest files of the repository without "todo.md"
2. Send the candidate the "todo.md" (or its information) seperately
3. Have the "todo.md" (or its information) inside the repo so it doesn't get out of sync.

The candidate doesn't NEED to have access to the repo at all as he is supposed to run the project locally.

**Comment by gilM2030** [comment]
Woops, I think I misunderstood a few things:

The `todo.md` you were initially talking about were the lines in the file right? 
I think the .zip should contain all the things the candidate needs to run the project locally (apart from maybe a quick `npm install`), if we want to not show some information, we can keep it in a separate branch, call it `solutions` for example and then we get the zip from `main/master` branch and that's what the candidate works on.

**Comment by akaztp** [comment]
> The `todo.md` you were initially talking about were the lines in the file right?

The file is the file "todo.md" created on this PR... Not sure I understand the question.

> I think the .zip should contain all the things the candidate needs to run the project locally (apart from maybe a quick `npm install`),

Of course. Up until now it would be:
https://github.com/2degrees/frontend-interview/archive/refs/heads/main.zip 

> if we want to not show some information, we can keep it in a separate branch, call it `solutions` for example and then we get the zip from `main/master` branch and that's what the candidate works on.

I think the user can not access the ".zip" link above with the repo being private, can he? So he doesn't go search for the repo and find the "solutions" branch.

**Comment by gilM2030** [comment]
OK, I think I'm understanding it all now, once you merge this PR, you'd like a way to not include the `to-do.md` file in the zip, which by default will be included given it's in the repository.

Could we move the to-do.md into wherever we store the template for the email to the candidate/document we talk the candidate throught? It'd be far from the code, but I assume we'll change the code more often than the todos.

**Comment by akaztp** [comment]
> OK, I think I'm understanding it all now, once you merge this PR, you'd like a way to not include the to-do.md file in the zip, which by default will be included given it's in the repository.

Yes!

> Could we move the to-do.md into wherever we store the template for the email to the candidate/document we talk the candidate throught!

We can.

> It'd be far from the code, but I assume we'll change the code more often than the todos.

The ToDo's refer lines of code, so they will surely be out of sync when changing the code. That is my main point.
We can use different referencing methods but I believe they introduce some needless friction.
But if that's the only option, it will have to do.

**Comment by akaztp** [comment]
Another idea would be to use a file sharing service with scheduled availability. We would make the zip without the "to-do.md" file manually.

**Comment by akaztp** [comment]
> Another idea would be to use a file sharing service with scheduled availability. We would make the zip without the "to-do.md" file manually.

I couldn't find it.

**Pull request merged**
